// CHECKSTYLE:OFF
/**
 * Source code generated by Fluent Builders Generator
 * Do not modify this file
 * See generator home page at: http://code.google.com/p/fluent-builders-generator-eclipse-plugin/
 */

package br.com.ingenieux.mojo.beanstalk.cmd.env.swap;

/*
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

public class SwapCNamesContextBuilder extends
                                      SwapCNamesContextBuilderBase<SwapCNamesContextBuilder> {

  public SwapCNamesContextBuilder() {
    super(new SwapCNamesContext());
  }

  public static SwapCNamesContextBuilder swapCNamesContext() {
    return new SwapCNamesContextBuilder();
  }

  public SwapCNamesContext build() {
    return getInstance();
  }
}

class SwapCNamesContextBuilderBase<GeneratorT extends SwapCNamesContextBuilderBase<GeneratorT>> {

  private SwapCNamesContext instance;

  protected SwapCNamesContextBuilderBase(SwapCNamesContext aInstance) {
    instance = aInstance;
  }

  protected SwapCNamesContext getInstance() {
    return instance;
  }

  @SuppressWarnings("unchecked")
  public GeneratorT withSourceEnvironmentName(String aValue) {
    instance.setSourceEnvironmentName(aValue);

    return (GeneratorT) this;
  }

  @SuppressWarnings("unchecked")
  public GeneratorT withSourceEnvironmentId(String aValue) {
    instance.setSourceEnvironmentId(aValue);

    return (GeneratorT) this;
  }

  @SuppressWarnings("unchecked")
  public GeneratorT withDestinationEnvironmentName(String aValue) {
    instance.setDestinationEnvironmentName(aValue);

    return (GeneratorT) this;
  }

  @SuppressWarnings("unchecked")
  public GeneratorT withDestinationEnvironmentId(String aValue) {
    instance.setDestinationEnvironmentId(aValue);

    return (GeneratorT) this;
  }
}
